[package]
name = "max-clique"
version = "0.1.0"
authors = ["Breno Viana <brenomfviana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.1", features = ["yaml"] }
dirs = "2.0.2"
